# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_userprofiledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField()),
                ('checked_out', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'cart_cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('object_id', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'cart_item',
            },
        ),
        migrations.AlterModelOptions(
            name='userprofiledetails',
            options={'managed': False},
        ),
    ]
