# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(db_column='id', default=0, primary_key=True, serialize=False),
        ),
    ]
