# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20171109_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
